version: '3.9'

services:
  metropolitan-api:
    container_name: metropolitan-api
    image: metropolitan-api:latest
    env_file:
      - .env
    build: 
      context: .
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    ports:
      - 3000:3000
    depends_on:
      - psql-db
    networks:
      - metropolitan-network
    
  psql-db:
    container_name: psql-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=metropolitan
      - POSTGRES_PASSWORD=123456
    networks:
      - metropolitan-network

networks:
  metropolitan-network: